name: app_6_2
description: App 6_2

version: 1.6.27

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.9.0
  bloc: ^8.1.0
  brasil_fields: ^1.1.2
  cached_network_image: ^3.1.0
  cloud_firestore: ^5.5.0
  collection: ^1.16.0
  community_charts_flutter: ^1.0.4
  connectivity_plus: ^6.0.3
  convex_bottom_bar: ^3.0.0
  cross_file: ^0.3.3+4
  currency_text_input_formatter: ^2.0.1
  dartz: ^0.10.1
  device_info_plus: ^11.1.1
  dio_http_cache: ^0.3.0
  dio: ^5.4.3+1
  direct_select: ^2.0.0
  due_date: ^2.2.1
  equatable: ^2.0.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  flutter_custom_clippers: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_signature_pad: ^3.0.1
  flutter_speed_dial: ^7.0.0
  flutter_spinbox: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^9.2.0
  grouped_list: ^6.0.0
  image: ^4.0.17
  intl: any
  location: ^7.0.1
  logging: ^1.0.1
  mailer: ^6.0.1
  mask_text_input_formatter: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^8.0.0
  path_provider: ^2.0.2
  path: ^1.8.1
  pdf: ^3.10.4
  percent_indicator: ^4.0.0
  provider: ^6.0.3
  scoped_model: ^2.0.0
  search_cep: ^4.0.2
  share_plus: ^10.1.2
  shared_preferences: ^2.0.13
  sqflite: ^2.0.0+3
  syncfusion_flutter_datepicker: ^27.2.4
  syncfusion_localizations: ^27.2.4
  time: ^2.1.3
  tutorial_coach_mark: ^1.0.3
  url_launcher: ^6.0.12
  validators: ^3.0.0
  wakelock_plus: ^1.2.5
  xml: ^6.1.0

  arquivos:
    path: ../../Packages/arquivos
  version:
    path: ../../Packages/version
  data_table:
    path: ../../Packages/data_table
  login:
    path: ../../Packages/login
  loading:
    path: ../../Packages/loading
  splashpage:
    path: ../../Packages/splashpage
  custom_fields:
    path: ../../Packages/custom_fields
  untraditional_dialog:
    path: ../../Packages/untraditional_dialog
  drawer:
    path: ../../Packages/drawer
  padrao:
    path: ../../Packages/padrao

flutter:
  uses-material-design: true
