name: app4
description: A new Flutter project.

version: 1.0.19

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  boxy: ^2.2.0
  cloud_firestore: ^5.4.4
  collection: ^1.17.0
  connectivity_plus: ^6.0.5
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.2
  drift_flutter: ^0.2.0
  drift: ^2.18.0
  due_date: ^2.0.0
  equatable: ^2.0.5
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_ui_localizations: ^1.6.0
  firebase_ui_oauth_google: ^1.2.9
  firebase_ui_oauth: ^1.4.9
  fl_chart: ^0.70.2
  flutter_spinbox: ^0.13.1
  google_sign_in: ^6.1.5
  graphs: ^2.3.1
  grouped_list: ^6.0.0
  intl: any
  logging: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.15.0
  path_provider: ^2.0.0
  path: ^1.8.2
  provider: ^6.0.5
  rxdart: ^0.27.7
  share_plus: ^10.0.2
  sqlite3_flutter_libs: ^0.5.0
  stack_trace: ^1.11.1
  time: ^2.1.4
  visibility_detector: ^0.4.0+2

  arquivos:
    path: "../../Packages/arquivos"
  network:
    path: "../../Packages/network"
  page_routing:
    path: "../../Packages/page_routing"
  loading:
    path: "../../Packages/loading"
  splashpage:
    path: "../../Packages/splashpage"
  login:
    path: "../../Packages/login"
  data_table:
    path: "../../Packages/data_table"
  drawer:
    path: "../../Packages/drawer"
  percentage_chart:
    path: "../../Packages/percentage_chart"
  adm_email_managing:
    path: "../../Packages/adm_email_managing"
  untraditional_dialog:
    path: "../../Packages/untraditional_dialog"
  version:
    path: "../../Packages/version"
  custom_fields:
    path: "../../Packages/custom_fields"
  graficos:
    path: "../../Packages/graficos"
  padrao:
    path: "../../Packages/padrao"

flutter:
  uses-material-design: true
