name: example_dart
description: A sample command-line application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  padrao:
    path: ./..

dev_dependencies:
  lints: ^6.0.0
