name: app1
description: App 1

version: 1.2.9

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.2
  cloud_firestore: ^5.4.4
  due_date: ^2.0.0
  equatable: ^2.0.3
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_launcher_icons: ^0.14.1
  flutter_signature_pad: ^3.0.1
  flutter_speed_dial: ^7.0.0
  http: ^1.2.0
  image: ^4.1.4
  intl: any
  location: ^7.0.1
  logging: ^1.0.1
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.0.5
  path: ^1.8.3
  percent_indicator: ^4.2.2
  provider: ^6.0.2
  shared_preferences: ^2.2.3
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.12
  wakelock_plus: ^1.3.2

  qr_processor:
    path: "../../Packages/qr_processor"
  padrao:
    path: "../../Packages/padrao"
  version:
    path: "../../Packages/version/"
  loading:
    path: "../../Packages/loading/"
  untraditional_dialog:
    path: "../../Packages/untraditional_dialog/"

flutter:
  uses-material-design: true
