name: app7
description: App7

publish_to: none

version: 1.2.8

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.8.1
  bloc: ^8.1.0
  cloud_firestore: ^5.4.4
  collection: ^1.16.0
  equatable: ^2.0.5
  expandable_page_view: ^1.0.8
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  firebase_remote_config: ^5.1.3
  flutter_easyloading: ^3.0.3
  flutter_offline: ^4.0.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.1.0
  google_sign_in: ^6.2.1
  grouped_list: ^6.0.0
  intl: any
  logging: ^1.0.1
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.0.0
  shared_preferences: ^2.0.11
  time: ^2.1.1
  url_launcher: ^6.1.7
  validators: ^3.0.0

  custom_fields:
    path: "../../Packages/custom_fields"
  beep:
    path: "../../Packages/beep"
  qr_processor:
    path: "../../Packages/qr_processor/"
  version:
    path: "../../Packages/version/"
  padrao:
    path: "../../Packages/padrao/"
  network:
    path: "../../Packages/network/"
  login:
    path: "../../Packages/login/"
  loading:
    path: "../../Packages/loading/"
  untraditional_dialog:
    path: "../../Packages/untraditional_dialog/"
  data_table:
    path: "../../Packages/data_table/"
  page_routing:
    path: "../../Packages/page_routing"
  graficos:
    path: "../../Packages/graficos"
  splashpage:
    path: "../../Packages/splashpage"
  drawer:
    path: "../../Packages/drawer"
  adm_email_managing:
    path: "../../Packages/adm_email_managing"

flutter:
  uses-material-design: true
