name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  provider: ^6.0.0
  qr_processor:
    path: '../'
  padrao:
    path: '../../padrao'
  flutter:
    sdk: flutter
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
