name: app3
description: A new Flutter project.

version: 1.4.2

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    version: any

  async: ^2.8.1
  bloc: ^8.1.4
  cloud_firestore: ^5.4.4
  collection: ^1.18.0
  cubit_form: ^3.0.2
  dio: ^5.1.1
  equatable: ^2.0.3
  expandable_page_view: ^1.0.8
  firebase_analytics: ^11.5.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.3.8
  flutter_easyloading: ^3.0.3
  flutter_layout_grid: ^2.0.1
  flutter_mobx: ^2.2.1+1
  flutter_signin_button: ^2.0.0
  flutter_speed_dial: ^7.0.0
  google_sign_in: ^6.1.0
  grouped_list: ^6.0.0
  intl: any
  logging: ^1.0.1
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.15.0
  mobx: ^2.3.3+2
  mqtt_client: ^10.5.0
  mqtt5_client: ^4.4.0
  provider: ^6.0.0
  shared_preferences: ^2.0.11
  time: ^2.1.4
  url_launcher: ^6.1.7
  validators: ^3.0.0

  qr_processor:
    path: "../../Packages/qr_processor"
  version:
    path: "../../Packages/version"
  custom_fields:
    path: "../../Packages/custom_fields"
  loading:
    path: "../../Packages/loading"
  network:
    path: "../../Packages/network"
  page_routing:
    path: "../../Packages/page_routing"
  untraditional_dialog:
    path: "../../Packages/untraditional_dialog"
  login:
    path: "../../Packages/login"
  splashpage:
    path: "../../Packages/splashpage"
  drawer:
    path: "../../Packages/drawer"
  adm_email_managing:
    path: "../../Packages/adm_email_managing"
  data_table:
    path: "../../Packages/data_table"
  padrao:
    path: "../../Packages/padrao"
  boxy: ^2.2.1

flutter:
  uses-material-design: true
