name: version
description: A new Flutter package project.
version: 0.0.1

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  url_launcher: ^6.1.11
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages

# dependency_overrides:
# Override any transitive dependencies here.
# For example, to override the version of the SDK used by a package:
# package_name:
#   sdk: ">=2.12.0 <3.0.0"
# To force a specific version of a package, even if it's not compatible with
# the current SDK, uncomment the following line and specify the version:
# package_name: ^1.2.3

# If your package is a Flutter plugin, uncomment the following line and
# specify the plugin's name:
# flutter:
#   plugin:
#     name: my_plugin
#     platforms:
#       android:
#         package: com.example.my_plugin
#         pluginClass: MyPlugin
#       ios:
#         pluginClass: MyPlugin
#       web:
#         pluginClass: MyPlugin

# To add support for additional platforms, uncomment the following lines and
# specify the platform's name and the corresponding package and plugin class:
# flutter:
#   plugin:
#     android:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     ios:
#       pluginClass: MyPlugin
#     web:
#       pluginClass: MyPlugin
#     linux:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     macos:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     windows:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin

# The following section is specific to Flutter web packages.
# flutter:
#   web:
#     renderer: canvaskit
#     enableServiceWorker: true
#     serviceWorker:
#       file: flutter_service_worker.js
#       scope: /

# The following section is specific to Flutter desktop packages.
# flutter:
#   desktop:
#     linux:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     macos:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     windows:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin

# The following section is specific to Flutter mobile packages.
# flutter:
#   mobile:
#     android:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     ios:
#       pluginClass: MyPlugin

# The following section is specific to Flutter web and mobile packages.
# flutter:
#   web:
#     renderer: canvaskit
#     enableServiceWorker: true
#     serviceWorker:
#       file: flutter_service_worker.js
#       scope: /
#   mobile:
#     android:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     ios:
#       pluginClass: MyPlugin

# The following section is specific to Flutter desktop and mobile packages.
# flutter:
#   desktop:
#     linux:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     macos:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     windows:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#   mobile:
#     android:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     ios:
#       pluginClass: MyPlugin

# The following section is specific to Flutter web, desktop, and mobile packages.
# flutter:
#   web:
#     renderer: canvaskit
#     enableServiceWorker: true
#     serviceWorker:
#       file: flutter_service_worker.js
#       scope: /
#   desktop:
#     linux:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     macos:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     windows:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#   mobile:
#     android:
#       package: com.example.my_plugin
#       pluginClass: MyPlugin
#     ios:
#       pluginClass: MyPlugin
