name: app5
description: App5

version: 0.1.0

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebase_core: ^3.8.0
  flutter_signin_button: ^2.0.0
  go_router: ^14.6.1
  google_sign_in: ^6.1.5
  intl: any
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.0.5

  loading:
    path: "../../Packages/loading"
  login:
    path: "../../Packages/login"
  version:
    path: "../../Packages/version"
  splashpage:
    path: "../../Packages/splashpage"
  untraditional_dialog:
    path: "../../Packages/untraditional_dialog"
  padrao:
    path: "../../Packages/padrao"
  collection: ^1.17.2

flutter:
  uses-material-design: true
