name: untraditional_dialog
description: A new Flutter package project.
version: 0.0.1

publish_to: none

resolution: workspace
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  logging: ^1.2.0
  equatable: ^2.0.5
  padrao:
    path: '../padrao'

flutter:
  uses-material-design: true
